/* Generated by AN DISI Unibo */ 
package it.unibo.led_actor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Led_actor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "off"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val frame = javax.swing.JFrame()
				frame.title = "Led"
				frame.defaultCloseOperation = javax.swing.WindowConstants.EXIT_ON_CLOSE
		   		frame.setSize(300, 200)
		   		frame.setLocation(30, 250)
		    	frame.contentPane.background = java.awt.Color.BLACK
		    	frame.isVisible = true
		return { //this:ActionBasciFsm
				state("off") { //this:State
					action { //it:State
						 frame.contentPane.background = java.awt.Color.BLACK  
					}
					 transition(edgeName="t_03",targetState="on",cond=whenDispatch("turn_on"))
				}	 
				state("on") { //this:State
					action { //it:State
						 frame.contentPane.background = java.awt.Color.YELLOW  
					}
					 transition(edgeName="t_04",targetState="off",cond=whenDispatch("turn_off"))
				}	 
			}
		}
}
