/* Generated by AN DISI Unibo */ 
package it.unibo.servicestatusactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Servicestatusactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("outdoorAlarm(N)"), Term.createTerm("outdoorAlarm(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Service Status GUI -> OUTDOOR alarm!")
						}
						if( checkMsgContent( Term.createTerm("outdoorAlarmRevoked(N)"), Term.createTerm("outdoorAlarmRevoked(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Service Status GUI -> OUTDOOR alarm REVOKED!")
						}
						if( checkMsgContent( Term.createTerm("temperatureAlarm(N)"), Term.createTerm("temperatureAlarm(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Service Status GUI -> Temperature alarm!")
						}
						if( checkMsgContent( Term.createTerm("temperatureAlarmRevoked(N)"), Term.createTerm("temperatureAlarmRevoked(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Service Status GUI -> Temperature alarm REVOKED!")
						}
					}
					 transition(edgeName="t10",targetState="s",cond=whenEvent("outdoorAlarm"))
					transition(edgeName="t11",targetState="s",cond=whenEvent("outdoorAlarmRevoked"))
					transition(edgeName="t12",targetState="s",cond=whenEvent("temperatureAlarm"))
					transition(edgeName="t13",targetState="s",cond=whenEvent("temperatureAlarmRevoked"))
				}	 
			}
		}
}
