/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iss2021_resumablebw;

import it.unibo.supports.RobotApplicationStarter;

public class App {

    public static void main(String[] args) {
        MySimpleDispatcher dispatcher = (MySimpleDispatcher) new RobotApplicationStarter().createInstance(MySimpleDispatcher.class);
        new MyConsoleGui(dispatcher);
    }

}
