/* Generated by AN DISI Unibo */ 
package it.unibo.trolleyactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Trolleyactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "idle"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val planner = carparking.DirectionalPlanner("parkingMap")
				val proxy = carparking.RobotProxy(this, "localhost")
				val home = arrayOf("0", "0", "S")
				val parking = arrayOf("1", "1", "E")
				val indoor = arrayOf("6", "0", "N")
				val outdoor = arrayOf("6", "4", "S")
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("goto(PLACE)"), Term.createTerm("goto(home)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								planner.planFor( home  )
						}
						if( checkMsgContent( Term.createTerm("goto(PLACE)"), Term.createTerm("goto(parking)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								planner.planFor( parking  )
						}
						if( checkMsgContent( Term.createTerm("goto(PLACE)"), Term.createTerm("goto(outdoor)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								planner.planFor( outdoor  )
						}
						if( checkMsgContent( Term.createTerm("goto(PLACE)"), Term.createTerm("goto(indoor)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								planner.planFor( indoor  )
						}
						stateTimer = TimerActor("timer_idle", 
							scope, context!!, "local_tout_trolleyactor_idle", 500.toLong() )
					}
					 transition(edgeName="t2",targetState="working",cond=whenTimeout("local_tout_trolleyactor_idle"))   
				}	 
				state("working") { //this:State
					action { //it:State
						 val move = planner.getNextPlannedMove()  
						if(  move.isNotEmpty()  
						 ){proxy.doMove( move  )
						planner.updateMap( move  )
						}
						else
						 {forward("movementDone", "movementDone(0)" ,"businesslogicactor" ) 
						 }
					}
					 transition(edgeName="t3",targetState="working",cond=whenDispatch("endmove"))
					transition(edgeName="t4",targetState="idle",cond=whenDispatch("goto"))
				}	 
			}
		}
}
