/* Generated by AN DISI Unibo */ 
package it.unibo.blinker_actor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Blinker_actor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "off"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("off") { //this:State
					action { //it:State
					}
					 transition(edgeName="t_00",targetState="blinking",cond=whenDispatch("click"))
				}	 
				state("blinking") { //this:State
					action { //it:State
						forward("turn_on", "turn_on(0)" ,"led_actor" ) 
						delay(500) 
						forward("turn_off", "turn_ff(0)" ,"led_actor" ) 
						stateTimer = TimerActor("timer_blinking", 
							scope, context!!, "local_tout_blinker_actor_blinking", 500.toLong() )
					}
					 transition(edgeName="t_01",targetState="blinking",cond=whenTimeout("local_tout_blinker_actor_blinking"))   
					transition(edgeName="t_02",targetState="off",cond=whenDispatch("click"))
				}	 
			}
		}
}
