/* Generated by AN DISI Unibo */ 
package it.unibo.trolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Trolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val planner = carparking.DirectionalPlanner("parkingMap")
				val proxy = carparking.RobotProxy(this, "localhost")
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 proxy.moveForward()  
						stateTimer = TimerActor("timer_s0", 
							scope, context!!, "local_tout_trolley_s0", 1000.toLong() )
					}
					 transition(edgeName="t00",targetState="s0",cond=whenTimeout("local_tout_trolley_s0"))   
				}	 
			}
		}
}
