/* Generated by AN DISI Unibo */ 
package it.unibo.businesslogicactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Businesslogicactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "moveToHome"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
		        val notice = "richiesta accettata"
		        var slotnum = 1
		        val tokenid = 1
		return { //this:ActionBasciFsm
				state("moveToHome") { //this:State
					action { //it:State
						forward("goto", "goto(home)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t0",targetState="acceptIN",cond=whenEvent("indoorOccupied"))
				}	 
				state("acceptIN") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="informIN", cond=doswitch() )
				}	 
				state("informIN") { //this:State
					action { //it:State
						if(  slotnum==1  
						 ){ slotnum--  
						}
						forward("msgInform", "msgInform(slotnum)" ,"parkservicegui" ) 
					}
					 transition( edgeName="goto",targetState="moveToIn", cond=doswitch() )
				}	 
				state("moveToIn") { //this:State
					action { //it:State
						forward("goto", "goto(indoor)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t1",targetState="receipt",cond=whenDispatch("movementDone"))
				}	 
				state("receipt") { //this:State
					action { //it:State
						forward("msgInform", "msgInform(tokenid)" ,"parkservicegui" ) 
					}
					 transition( edgeName="goto",targetState="moveToSlotIn", cond=doswitch() )
				}	 
				state("moveToSlotIn") { //this:State
					action { //it:State
						forward("goto", "goto(parking)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t2",targetState="moveToHome",cond=whenDispatch("movementDone"))
				}	 
				state("acceptOUT") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="findSlot", cond=doswitch() )
				}	 
				state("findSlot") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="moveToSlotOut", cond=doswitch() )
				}	 
				state("moveToSlotOut") { //this:State
					action { //it:State
						forward("goto", "goto(parking)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t3",targetState="moveToOut",cond=whenDispatch("movementDone"))
				}	 
				state("moveToOut") { //this:State
					action { //it:State
						forward("goto", "goto(outdoor)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t4",targetState="moveToHome",cond=whenDispatch("movementDone"))
				}	 
			}
		}
}
