/* Generated by AN DISI Unibo */ 
package it.unibo.businesslogicactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Businesslogicactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "moveToHome"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val notice = "richiesta accettata"
				val slotnum = 1
		return { //this:ActionBasciFsm
				state("moveToHome") { //this:State
					action { //it:State
						forward("goto", "goto(outdoor)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t0",targetState="acceptIN",cond=whenDispatch("movementDone"))
				}	 
				state("acceptIN") { //this:State
					action { //it:State
						forward("goto", "goto(parking)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t1",targetState="moveToHome",cond=whenDispatch("movementDone"))
				}	 
			}
		}
}
