/* Generated by AN DISI Unibo */ 
package it.unibo.autofan

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Autofan ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "idle"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t7",targetState="working",cond=whenEvent("temperature"))
				}	 
				state("working") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("temperature(VALUE)"), Term.createTerm("temperature(30)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("fanStop", "fanStop(0)" ,"fanactor" ) 
						}
						if( checkMsgContent( Term.createTerm("temperature(VALUE)"), Term.createTerm("temperature(40)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("fanStart", "fanStart(0)" ,"fanactor" ) 
						}
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
}
